# Makefile for the books phase 2 assignment
#     @author Yuting Su(suy@carelton.edu)
#     @author Starr Wang(wangy3@carleton.edu)
#      2018-09-20


test:
	echo "==== Testing booksdatasource.py by running booksdatesourcetest.py ===="
	python3 booksdatasourcetest.py